import { generateLayout } from "./gridGenerator.js";

const HOP_MS = 120;
const HOLD_MS = 260;
const RESTART_HOLD_MS = 1100;
const RESTART_FADE_MS = 300;

function drawMsFor(word) {
  return Math.min(1500, 650 + word.length * 55);
}

export class AnimationController {
  constructor({ renderer, tokens, rows, cols }) {
    this.renderer = renderer;
    this.tokens = tokens;
    this.rows = rows;
    this.cols = cols;
    this.active = false;
    this.index = 0;
    this.timeoutId = null;
    this.grid = null;
    this.placements = [];
  }

  start({ shuffle = false } = {}) {
    this.active = true;
    this._newLayout(shuffle);
    this._step();
  }

  stop() {
    this.active = false;
    clearTimeout(this.timeoutId);
  }

  _newLayout(shuffle = false) {
    const { grid, placements } = generateLayout(this.tokens, this.rows, this.cols, "auto");
    const hadGrid = Boolean(this.grid);
    this.grid = grid;
    this.placements = placements;
    this.renderer.fitToContainer(grid.rows, grid.cols);
    this.renderer.clearCapsules();
    this.index = 0;
    if (shuffle && hadGrid) {
      this.renderer.shuffleToLetters(grid);
    } else {
      this.renderer.renderLetters(grid);
    }
  }

  _step() {
    if (!this.active) return;

    if (this.index >= this.placements.length) {
      this.timeoutId = setTimeout(() => {
        if (!this.active) return;
        this._fadeAndRestart();
      }, RESTART_HOLD_MS);
      return;
    }

    const placement = this.placements[this.index];

    this.timeoutId = setTimeout(() => {
      if (!this.active) return;
      this.renderer.animateDraw(placement, drawMsFor(placement.word), () => {
        if (!this.active) return;
        this.timeoutId = setTimeout(() => {
          if (!this.active) return;
          this.index += 1;
          this._step();
        }, HOLD_MS);
      });
    }, HOP_MS);
  }

  // Loops the same puzzle (same letters, same placements) — a fresh layout
  // only ever gets generated by start(), i.e. when the user toggles away to
  // "Who I've worked with" and back, never on its own after a full pass.
  _fadeAndRestart() {
    this.renderer.clearCapsules();
    this.timeoutId = setTimeout(() => {
      if (!this.active) return;
      this.index = 0;
      this._step();
    }, RESTART_FADE_MS);
  }
}
